parameters:
  socloz.nsq.delayed.topic_name: __socloz_delayed

services:
  socloz.nsq.logger:
    class: Socloz\NsqBundle\Logger\MonologAdapter
    arguments: ["@logger"]
  socloz.nsq:
    class: Socloz\NsqBundle\Topic\Manager
    lazy: true
    arguments:
      - %socloz.nsq.delayed.topic_name%
      - "@?socloz.nsq.lookup"
      - "@socloz.nsq.logger"
  socloz.nsq.delayed_messages.consumer:
    class: Socloz\NsqBundle\Delayed\Consumer
    lazy: true
    arguments: ["@socloz.nsq"]
    tags:
    -  { name: socloz.nsq.consumer, topic: %socloz.nsq.delayed.topic_name%, channel: default }
